### ISSUE TITLE
Unsafe code

### ISSUE THREAD

**Issue by dbechrd** [rwxrob/head-first-c-projects#3]
You have a buffer overflow somewhere in your code, but I'll leave finding it as an exercise to the reader. ;)

**Comment by Frank-Buss** [comment]
I don't see a buffer overflow. But I would still consider it unsafe code, because the 20 and 19 in adios.c are just magic numbers in the source code. If someday someone changes the string size, then it can overflow.

Either use a define constant at the top (but which requires a stringify macro to concatenate the format string), or something like this, instead of scanf:
```
fgets(ex, sizeof(ex) / sizeof(char) - 1, stdin);
```

This is somewhat related to the DRY principle (don't repeat yourself) : 
https://en.wikipedia.org/wiki/Don%27t_repeat_yourself
The important part of it:
> a modification of any single element of a system does not require a change in other logically unrelated elements
